<a href="https://colab.research.google.com/github/kumar-shivang/PyTorch-Tutorial/blob/master/fundamentals/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
It is the first chapter of the pytorch tutorial I am following. Let's dive into the basics of PyTorch.

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Importing Pytorch

In [3]:
import torch
print(torch.__version__)

2.3.0+cu121


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Creating Tensors
### Scalars

In [5]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

1

### Vectors

In [8]:
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [9]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

### Matrix

In [14]:
matrix = torch.tensor([[1,1],[1,1]])
matrix

tensor([[1, 1],
        [1, 1]])

In [15]:
matrix.shape

torch.Size([2, 2])

In [17]:
matrix.ndim

2

### Tensor

In [18]:
tensor = torch.tensor([[[1,1],[1,1]],[[1,1],[1,1]]])
tensor

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])

In [19]:
tensor.shape

torch.Size([2, 2, 2])

In [20]:
tensor.ndim

3