<a href="https://colab.research.google.com/github/kumar-shivang/PyTorch-Tutorial/blob/master/fundamentals/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
It is the first chapter of the pytorch tutorial I am following. Let's dive into the basics of PyTorch.

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Importing Pytorch

In [2]:
import torch
print(torch.__version__)

2.3.0+cu121


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Creating Tensors
### Scalars

In [4]:
scalar = torch.tensor(1)
scalar

tensor(1)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

1

### Vectors

In [7]:
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

### Matrix

In [10]:
MATRIX = torch.tensor([[1,1],[1,1]])
MATRIX

tensor([[1, 1],
        [1, 1]])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX.ndim

2

### Tensor

In [13]:
TENSOR = torch.tensor([[[1,1],[1,1]],[[1,1],[1,1]]])
TENSOR

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]])

In [14]:
TENSOR.shape

torch.Size([2, 2, 2])

In [15]:
TENSOR.ndim

3